name: Build and Test

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  check-application:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests with Gradle
      run: ./gradlew test